# configs/config_steps_i2i.yaml

models:
  - name: "sd2"
    path: "models/stabilityai/stable-diffusion-2-1"
  - name: "sdxl"
    path: "models/stabilityai/stable-diffusion-xl-base-1.0"
  # - name: "sd3"
  #   path: "models/stabilityai/stable-diffusion-3-medium-diffusers"
  - name: "instruct-pix2pix"
    path: "models/timbrooks/instruct-pix2pix"

data:
  ref_image: "data/samples/hurricane-matthew_00000066_2_pre_disaster.png"
  output_folder: "out/ablation_steps_i2i"

ablation_config:
  inference_steps: [20, 40, 60, 80, 100]
  height: 512
  width: 512
  guidance_scale: 7.0
  prompt: "A satellite image of residential suffering from severe hurricane in Haiti"
  seed: 0

logging:
  log_file: "log/ablation_steps_i2i.log"
