# configs/config_steps_t2i.yaml

models:
  - name: "sd2"
    path: "models/stabilityai/stable-diffusion-2-1"
  - name: "sdxl"
    path: "models/stabilityai/stable-diffusion-xl-base-1.0"
  - name: "sd3"
    path: "models/stabilityai/stable-diffusion-3-medium-diffusers"
  - name: "diffusionsat"
    path: "models/fsx/proj-satdiffusion/finetune_sd21_sn-satlas-fmow_snr5_md7norm_bs64"

data:
  output_folder: "out/ablation_steps_t2i"

ablation_config:
  inference_steps: [20,40,60,80,100]
  height: 512
  width: 512
  guidance_scale: 7.0
  prompt: "A satellite image of farmland suffering from severe flooding in India"
  seed: 0

logging:
  log_file: "log/ablation_steps_t2i.log"
